kind: ReplicationController
apiVersion: v1
metadata:
  name: spark-worker-controller
spec:
  replicas: 2
  selector:
    component: spark-worker
  template:
    metadata:
      labels:
        component: spark-worker
    spec:
      containers:
        - name: spark-worker
          image: gcr.io/google_containers/spark:1.5.2_v1
          command: ["/start-worker"]
          ports:
            - containerPort: 8081
          resources:
            requests:
              cpu: 100m
          volumeMounts:
            - name: nfsvol
              mountPath: /usr/share/nfs_spark
      volumes:
        - name: nfsvol
          nfs:
            path: /opt/nfsshare
            server: 192.168.121.10
            readOnly: true


